FROM python:3.6-alpine3.7

RUN apk add --no-cache --update \
    python3 python3-dev gcc \
    gfortran musl-dev g++ \
    libffi-dev openssl-dev \
    libxml2 libxml2-dev \
    libxslt libxslt-dev \
    libjpeg-turbo-dev zlib-dev

RUN pip install --upgrade cython
RUN pip install --upgrade pip
RUN pip install numpy==1.17.1
RUN pip install pandas==0.25.1


WORKDIR /usr/src/app
COPY . .

CMD ["docker_pandas.py"]
ENTRYPOINT ["python3"]
