CREATE TABLE IF NOT EXISTS yahoofinance (
    symbol_short text,
    inserted timestamp(0) without time zone NOT NULL,
    language text,
    region text,
    quoteType text,
    quoteSourceName text,
    triggerable bool,
    currency text,
    fiftyTwoWeekLowChange NUMERIC(15, 10),
    fiftyTwoWeekLowChangePercent NUMERIC(15, 10),
    fiftyTwoWeekRange text,
    fiftyTwoWeekHighChange NUMERIC(15, 10),
    fiftyTwoWeekHighChangePercent NUMERIC(15, 10),
    fiftyTwoWeekLow NUMERIC(15, 10),
    fiftyTwoWeekHigh NUMERIC(15, 10),
    dividendDate NUMERIC(30, 0),
    trailingAnnualDividendRate NUMERIC(15, 10),
    trailingPE NUMERIC(15, 10),
    trailingAnnualDividendYield NUMERIC(15, 10),
    epsTrailingTwelveMonths NUMERIC(15, 10),
    marketState text,
    exchange text,
    longName text,
    messageBoardId text,
    exchangeTimezoneName text,
    exchangeTimezoneShortName text,
    gmtOffSetMilliseconds NUMERIC(30, 0),
    market text,
    esgPopulated bool,
    epsForward NUMERIC(15, 10),
    sharesOutstanding NUMERIC(30, 0),
    bookValue NUMERIC(15, 10),
    fiftyDayAverage NUMERIC(15, 10),
    fiftyDayAverageChange NUMERIC(15, 10),
    fiftyDayAverageChangePercent NUMERIC(15, 10),
    twoHundredDayAverage NUMERIC(15, 10),
    twoHundredDayAverageChange NUMERIC(15, 10),
    twoHundredDayAverageChangePercent NUMERIC(15, 10),
    marketCap NUMERIC(30, 0),
    forwardPE NUMERIC(15, 10),
    priceToBook NUMERIC(15, 10),
    sourceInterval NUMERIC(15, 0),
    exchangeDataDelayedBy NUMERIC(15, 0),
    averageAnalystRating text,
    tradeable bool,
    firstTradeDateMilliseconds NUMERIC(30, 0),
    priceHint NUMERIC(15, 10),
    shortName text,
    symbol text
);
